name: base
channels:
  - jhedrick
  - conda-forge/label/gcc7
  - conda-forge
  - defaults
dependencies:
  - joblib=1.1.1=py39haa95532_0
  - pandas=1.4.4=py39hd77b12b_0
  - scikit-learn=1.1.3=py39hd77b12b_0
  - streamlit==1.21.0
  - pip:

      - streamlit==1.21.0